version: "3"
services:
  healthChecker:
    build: 
      context: .
      dockerfile: "./Server/Dockerfile"
    environment:
      - BOT_VERSION=4.0
      - SEND_MESSAGE="ãŠç–²ã‚Œæ§˜ã§ã—ãŸâ™ª\néƒ¨æ´»å‹•ã«å‚åŠ ã•ã‚ŒãŸæ–¹ã¯ãƒªã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã‚’ãŠé¡˜ã„ã—ã¾ã™â™ª\nè‰¯å¥½â‡’ğŸ‘Œ ä¸è‰¯â‡’ğŸ˜«\n@everyone"
    secrets:
      - botConfig
  
  secrets:
  botConfig:
    file: config.csv